train:
  type: "EfficientADCuvisDataSet"
  params:
    dataset_dir: ./data/Hyperspektral-Small/bedding_dataset
    mode: "train"
    imagenet_dir: ./data/ImageNet_6_channel
    imagenet_file_ending: ".npy"
    in_channels: 6
    normalize: true
    max_img_shape: 1500
    white_percentage: 0.55
    channels: "ALL"
    mean: [0.0267, 0.0267, 0.0267, 0.0267, 0.0267, 0.0267]
    std:  [0.0137, 0.0137, 0.0137, 0.0137, 0.0137, 0.0137]
    obtain:
      hf:
        repo_id: nghorbani/Hyperspektral-Small
        local_dir: data/Hyperspektral-Small

val:
  type: "EfficientADCuvisDataSet"
  params:
    dataset_dir: ./data/Hyperspektral-Small/bedding_dataset
    mode: "test"
    imagenet_dir: ./data/ImageNet_6_channel
    imagenet_file_ending: ".npy"
    in_channels: 6
    normalize: true
    max_img_shape: 1500
    white_percentage: 0.55
    channels: "ALL"
    mean: [0.0267, 0.0267, 0.0267, 0.0267, 0.0267, 0.0267]
    std:  [0.0137, 0.0137, 0.0137, 0.0137, 0.0137, 0.0137]
    obtain:
      hf:
        repo_id: nghorbani/Hyperspektral-Small
        local_dir: data/Hyperspektral-Small

test:
  type: "EfficientADCuvisDataSet"
  params:
    dataset_dir: ./data/Hyperspektral-Small/bedding_dataset
    mode: "test"
    imagenet_dir: ./data/ImageNet_6_channel
    imagenet_file_ending: ".npy"
    in_channels: 6
    normalize: true
    max_img_shape: 1500
    white_percentage: 0.55
    channels: "ALL"
    mean: [0.0267, 0.0267, 0.0267, 0.0267, 0.0267, 0.0267]
    std:  [0.0137, 0.0137, 0.0137, 0.0137, 0.0137, 0.0137]
    obtain:
      hf:
        repo_id: nghorbani/Hyperspektral-Small
        local_dir: data/Hyperspektral-Small
