type: EfficientADCuvisDataSet
params:
  path: data/bedding_dataset
  mode: train
  imageNet_path: data/ImageNet
  imageNet_file_ending: .npy
  in_channels: 6
  mean: null
  std: null
  normalize: true
  max_img_shape: 1500
  white_percentage: 0.55
  channels: ALL
