
train:
  type: PerPixelAECuvisDataSet
  params:
    dataset_dir: data/Hyperspektral-Small
    mode: train
    max_img_shape: 1500
    channels: ALL
    white_percentage: 0.55
    normalize: true
    mean: null
    std: null
    obtain:
      hf:
        repo_id: nghorbani/HyperspectralTiny
        local_dir: data/Hyperspektral-Small

val:
  type: PerPixelAECuvisDataSet
  params:
    dataset_dir: data/Hyperspektral-Small
    mode: test
    max_img_shape: 1500
    channels: ALL
    white_percentage: 0.55
    normalize: true
    mean: null
    std: null
    obtain:
      hf:
        repo_id: nghorbani/HyperspectralTiny
        local_dir: data/Hyperspektral-Small

test:
  type: PerPixelAECuvisDataSet
  params:
    dataset_dir: data/Hyperspektral-Small
    mode: test
    max_img_shape: 1500
    channels: ALL
    white_percentage: 0.55
    normalize: true
    mean: null
    std: null
    obtain:
      hf:
        repo_id: nghorbani/HyperspectralTiny
        local_dir: data/Hyperspektral-Small
