
train:
  type: PerPixelAECuvisDataSet
  params:
    variant: "tiny"
    dataset_dir: data/cubes
    mode: train
    max_img_shape: 1500
    channels: ALL
    white_percentage: 0.55
    normalize: true
    mean: null
    std: null

val:
  type: PerPixelAECuvisDataSet
  params:
    variant: "tiny"
    dataset_dir: data/cubes
    mode: test
    max_img_shape: 1500
    channels: ALL
    white_percentage: 0.55
    normalize: true
    mean: null
    std: null

test:
  type: PerPixelAECuvisDataSet
  params:
    variant: "tiny"
    dataset_dir: data/cubes
    mode: test
    max_img_shape: 1500
    channels: ALL
    white_percentage: 0.55
    normalize: true
    mean: null
    std: null
