train:
  type: StrawberryDataset
  params:
    root_dir: data/strawberry
    normalize: false
    cube_size: [200, 200]
    cube_rgb_channels: [4, 12, 25]
    days_to_exclude: [28]
    strawberry_range: [0, 220]
    sides_to_exclude: []
    mean: null
    std: null
    white_path: null
    dark_path: null

val:
  type: StrawberryDataset
  params:
    root_dir: data/strawberry
    normalize: false
    cube_size: [200, 200]
    cube_rgb_channels: [4, 12, 25]
    days_to_exclude: [28]
    strawberry_range: [0, 220]
    sides_to_exclude: []
    mean: null
    std: null
    white_path: null
    dark_path: null

test:
  type: StrawberryDataset
  params:
    root_dir: data/strawberry
    normalize: false
    cube_size: [200, 200]
    cube_rgb_channels: [4, 12, 25]
    days_to_exclude: [28]
    strawberry_range: [0, 220]
    sides_to_exclude: []
    mean: null
    std: null
    white_path: null
    dark_path: null
