defaults:
  - _self_
  - eval: efficientad
  - reporting: efficientad

inputs:
  preds_dir: ${work_dir}/preds
  gts_dir: ${work_dir}/gts

outputs:
  out_dir: ${work_dir}/reports

work_dir: ${oc.env:WORK_DIR, ./work_dirs/exp}
