defaults:
  - model: efficientad/medium
  - dataset: efficientad_train_val
  - runner: lightning
  - eval: default
  - logging: tensorboard
  - _self_

work_dir: ${oc.env:WORK_DIR, ./work_dirs/exp}
seed: 42
log_level: INFO
logging:
  verbose: false

trainer:
  max_epochs: 1
  accelerator: cuda

dataloader:
  batch_size: 1
  num_workers: 2

datasets:
  train: ${dataset.train}
  val: ${dataset.val}
